name: Trigger auto deployment for imbot24

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/imbot24-AutoDeployTrigger-3c938fba-1cb0-4392-8f67-7e119f99d726.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.IMBOT24_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: thimbot.azurecr.io
          registryUsername: ${{ secrets.IMBOT24_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IMBOT24_REGISTRY_PASSWORD }}
          containerAppName: imbot24
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: thimbot.azurecr.io/imbot24:${{ github.sha }}
          
            

     

